#!/usr/bin/env python3
"""Regenerate internal/library/systems.go from ES-DE's own systems list.

The library lays a ROM store out the way ES-DE (and RetroDECK, which ships
it) reads one: a folder per system, named as ES-DE names it, and every
system lists the file extensions it takes. That table is upstream's, not
ours - this script pulls it from the RetroDECK fork of ES-DE (the one a
RetroDECK seat runs) and writes it as Go, so the binary carries it and a
push can tell `.sfc` from `.iso` without asking anybody.

    python3 tools/es-systems.py            # fetch + write
    python3 tools/es-systems.py FILE.xml   # from a local copy
"""
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET

SOURCE = "https://raw.githubusercontent.com/RetroDECK/ES-DE/retrodeck-main/resources/systems/linux/es_systems.xml"
OUT = "internal/library/systems.go"


def main() -> None:
    if len(sys.argv) > 1:
        data = open(sys.argv[1], "rb").read()
    else:
        with urllib.request.urlopen(SOURCE, timeout=30) as r:
            data = r.read()
    root = ET.fromstring(data)
    rows = []
    for s in root.findall("system"):
        name = (s.findtext("name") or "").strip()
        full = (s.findtext("fullname") or name).strip()
        exts = sorted({e.lower() for e in (s.findtext("extension") or "").split() if e.startswith(".")})
        if not name:
            continue
        rows.append((name, full, exts))
    rows.sort()
    with open(OUT, "w") as f:
        f.write("// Code generated by tools/es-systems.py from ES-DE's es_systems.xml; DO NOT EDIT.\n\n")
        f.write("package library\n\n")
        f.write("// systems is ES-DE's own table (the RetroDECK fork): the folder a system's\n")
        f.write("// ROMs live in, what the menu calls it, and the extensions it takes -\n")
        f.write("// lower-cased, with the dot. %d systems.\n" % len(rows))
        f.write("var systems = []System{\n")
        for name, full, exts in rows:
            # a label with a dotted word in it reads like a hostname to the
            # repo's gate: it is upstream's own name for a console, so mark it
            mark = " // upstream's own name, not a host - no-environment: ok" if re.search(r"[A-Za-z0-9]\.[a-z]{2,}\b", full) else ""
            f.write("\t{Name: %s, Label: %s, Extensions: []string{%s}},%s\n" % (
                gostr(name), gostr(full), ", ".join(gostr(e) for e in exts), mark))
        f.write("}\n")
    print("%s: %d systems" % (OUT, len(rows)))


def gostr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
